@echo off 
echo zncmxzccmzvcnmzcznbcbcncbzcnbcxncbxcbxncxbcnxc
ccbxcnzncmzNXmZNzcbMNCBCNmNCBCMCnCBMCBCmmzmnzmcncbz
nmc,m,cmzczmc,cmz,cmcz,cmxz,ccncmcnvvbcnvbnbznbcnzcbnc
bcnxcbxncxzmcxzncxzcbzcmnxzczxncxzxcz,m
xbmxnxmnzmznmcbznczxbcxnc xmcxcncnxmc xmxnmx